version: '3.3'

services:
  db:
    container_name: mysql-container
    image: mysql:5.7
    volumes:
       - ./data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
     - "3306:3306"
    networks:
     - wordpress_net

  wordpress:
    container_name: wordpress-container
    volumes:
      - "./html:/var/www/html"
    depends_on:
      - db
    image: wordpress:php7.3-apache
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress_net
networks:
  wordpress_net:
